version: "2"
networks:
    # This special network is configured so that the local metadata
    # service can bind to the specific IP address that ECS uses
    # in production
    credentials_network:
        driver: bridge
        ipam:
            config:
                - subnet: "169.254.170.0/24"
                  gateway: 169.254.170.1
services:
    # This container vends credentials to your containers
    ecs-local-endpoints:
        # The Amazon ECS Local Container Endpoints Docker Image
        image: amazon/amazon-ecs-local-container-endpoints:latest-amd64
        volumes:
          # Mount /var/run so we can access docker.sock and talk to Docker
          - /var/run:/var/run
          # Mount the shared configuration directory, used by the AWS CLI and AWS SDKs
          # On Windows, this directory can be found at "%UserProfile%\.aws"
          - $HOME/.aws/:/home/.aws/
        environment:
          # define the home folder; credentials will be read from $HOME/.aws
          HOME: "/home"
          # You can change which AWS CLI Profile is used
          AWS_PROFILE: "surveystream_dev"
        networks:
            credentials_network:
                # This special IP address is recognized by the AWS SDKs and AWS CLI 
                ipv4_address: "169.254.170.2"
                
    # Here we reference the application container that we are testing
    # You can test multiple containers at a time, simply duplicate this section
    # and customize it for each container, and give it a unique IP in 'credentials_network'.
    superset:
        depends_on:
            - ecs-local-endpoints
        networks:
            credentials_network:
                ipv4_address: "169.254.170.24"
        environment:
          AWS_DEFAULT_REGION: "ap-south-1"
          AWS_CONTAINER_CREDENTIALS_RELATIVE_URI: "/role/superset-task-role"

    superset_worker:
        depends_on:
            - ecs-local-endpoints
        networks:
            credentials_network:
                ipv4_address: "169.254.170.23"
        environment:
          AWS_DEFAULT_REGION: "ap-south-1"
          AWS_CONTAINER_CREDENTIALS_RELATIVE_URI: "/role/superset-task-role"

    superset_flower:
        depends_on:
            - ecs-local-endpoints
        networks:
            credentials_network:
                ipv4_address: "169.254.170.22"
        environment:
          AWS_DEFAULT_REGION: "ap-south-1"
          AWS_CONTAINER_CREDENTIALS_RELATIVE_URI: "/role/superset-task-role"

    superset_beat:
        depends_on:
            - ecs-local-endpoints
        networks:
            credentials_network:
                ipv4_address: "169.254.170.21"
        environment:
          AWS_DEFAULT_REGION: "ap-south-1"
          AWS_CONTAINER_CREDENTIALS_RELATIVE_URI: "/role/superset-task-role"

    superset_postgres:
        networks:
            credentials_network:
                # define an alias for service discovery
                aliases:
                    - superset_postgres
                ipv4_address: "169.254.170.20"
    
    superset_redis:
        networks:
            credentials_network:
                # define an alias for service discovery
                aliases:
                    - redis
                ipv4_address: "169.254.170.19"