x-superset-depends-on: &superset-depends-on
  - db
  - redis
x-superset-volumes:
  &superset-volumes # /app/pythonpath_docker will be appended to the PYTHONPATH in the final container
  - ./docker:/app/docker
  - superset_home:/app/superset_home

x-common-build: &common-build
  context: .
  target: dev
  cache_from:
    - apache/superset-cache:3.10-slim-bookworm

version: '4.0'
services:
  redis:
    image: redis:7
    container_name: superset_cache
    restart: unless-stopped
    volumes:
      - redis:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
      env_file:
        - path: docker/.env
          required: true
      image: postgres:16.2
      environment:
        POSTGRES_DB: superset
        POSTGRES_PASSWORD: superset
        POSTGRES_USER: superset
      extra_hosts:
        - "host.docker.internal:host-gateway"
      ports:
        - "5432:5432"
      command: -p 5432
      volumes:
      - db_home:/var/lib/postgresql/data
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  superset:
    env_file:
      - path: docker/.env # default
        required: true
    build:
      <<: *common-build
    environment:
      - ADMIN_ACCOUNT=${ADMIN_ACCOUNT}
    container_name: superset
    user: "root"
    # command: webserver
    ports:
      - "8088:8088"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on: *superset-depends-on
    volumes: *superset-volumes
  superset_worker:
    # image: superset:latest
    build:
      <<: *common-build
    depends_on:
      - db
      - superset
      - redis
    environment:
      - ADMIN_ACCOUNT=${ADMIN_ACCOUNT}
    command: celery worker -B -l info -A app.tasks.celery
    links: 
      - "superset:superset"
    extra_hosts:
    - "host.docker.internal:host-gateway"
    

  superset_flower:
    build:
      <<: *common-build
    depends_on:
      - db
      - redis
      - superset
    environment:
      - ADMIN_ACCOUNT=${ADMIN_ACCOUNT}
    command: celery --broker=amqp://guest:guest@localhost:5672// flower
    extra_hosts:
    - "host.docker.internal:host-gateway"

  superset_beat:
    build:
      <<: *common-build
    depends_on:
      - db
      - redis
      - superset
    environment:
      - ADMIN_ACCOUNT=${ADMIN_ACCOUNT}
    command: celery beat
    extra_hosts:
    - "host.docker.internal:host-gateway"
volumes:
  redis:
    external: false
  superset_home:
    external: false
  db_home:
    external: false
